/*
 * This file is generated by jOOQ.
 */
package dev.byli.robot.archetype.infrastructure.repository.jooq;


import dev.byli.robot.archetype.infrastructure.repository.jooq.tables.Dummy;
import dev.byli.robot.archetype.infrastructure.repository.jooq.tables.records.DummyRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DummyRecord> DUMMY_PKEY = Internal.createUniqueKey(Dummy.DUMMY, DSL.name("dummy_pkey"), new TableField[] { Dummy.DUMMY.ID }, true);
}
