/*
 * This file is generated by jOOQ.
 */
package dev.byli.robot.archetype.infrastructure.repository.jooq;


import dev.byli.robot.archetype.infrastructure.repository.jooq.tables.Dummy;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.dummy</code>.
     */
    public static final Dummy DUMMY = Dummy.DUMMY;
}
