/*
 * This file is generated by jOOQ.
 */
package dev.byli.robot.archetype.infrastructure.repository.jooq.tables.records;


import dev.byli.robot.archetype.infrastructure.repository.jooq.tables.Dummy;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DummyRecord extends UpdatableRecordImpl<DummyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.dummy.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.dummy.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.dummy.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.dummy.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.dummy.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.dummy.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DummyRecord
     */
    public DummyRecord() {
        super(Dummy.DUMMY);
    }

    /**
     * Create a detached, initialised DummyRecord
     */
    public DummyRecord(Long id, String name, String description) {
        super(Dummy.DUMMY);

        setId(id);
        setName(name);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
