/*
 * This file is generated by jOOQ.
 */
package dev.byli.robot.archetype.infrastructure.repository.jooq.tables;


import dev.byli.robot.archetype.infrastructure.repository.jooq.Keys;
import dev.byli.robot.archetype.infrastructure.repository.jooq.Public;
import dev.byli.robot.archetype.infrastructure.repository.jooq.tables.records.DummyRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Dummy extends TableImpl<DummyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.dummy</code>
     */
    public static final Dummy DUMMY = new Dummy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DummyRecord> getRecordType() {
        return DummyRecord.class;
    }

    /**
     * The column <code>public.dummy.id</code>.
     */
    public final TableField<DummyRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.dummy.name</code>.
     */
    public final TableField<DummyRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.dummy.description</code>.
     */
    public final TableField<DummyRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Dummy(Name alias, Table<DummyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Dummy(Name alias, Table<DummyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.dummy</code> table reference
     */
    public Dummy(String alias) {
        this(DSL.name(alias), DUMMY);
    }

    /**
     * Create an aliased <code>public.dummy</code> table reference
     */
    public Dummy(Name alias) {
        this(alias, DUMMY);
    }

    /**
     * Create a <code>public.dummy</code> table reference
     */
    public Dummy() {
        this(DSL.name("dummy"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DummyRecord, Long> getIdentity() {
        return (Identity<DummyRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DummyRecord> getPrimaryKey() {
        return Keys.DUMMY_PKEY;
    }

    @Override
    public Dummy as(String alias) {
        return new Dummy(DSL.name(alias), this);
    }

    @Override
    public Dummy as(Name alias) {
        return new Dummy(alias, this);
    }

    @Override
    public Dummy as(Table<?> alias) {
        return new Dummy(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Dummy rename(String name) {
        return new Dummy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dummy rename(Name name) {
        return new Dummy(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dummy rename(Table<?> name) {
        return new Dummy(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dummy where(Condition condition) {
        return new Dummy(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dummy where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dummy where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dummy where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dummy where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dummy where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dummy where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dummy where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dummy whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dummy whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
